apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c2VjcmV0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "no"
  MYSQL_DATABASE: my-db
