apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-test
spec: 
  selector: 
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80