apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  completions: 4
  parallelism: 2
  template:
    metadata:
      name: example-job
    spec:
      restartPolicy: Never
      containers:
        - name: job-container
          image: busybox:latest
          command: ["echo", "Hello"]
