apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
 containers:
 - name: db-container
   image: mysql:latest
   env: 
   - name: MYSQL_ROOT_PASSWORD
     value: secret
   ports:
   - containerPort: 3306