apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - name: volume-nginx
          mountPath: /mnt/data
  volumes:
    - name: volume-nginx
      persistentVolumeClaim:
        claimName: volume2-claim
