apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume2-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  selector: 
     matchLabels:
       type: local2