apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume3
  labels:
    type: local3
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/docker/volumes/volume3
