apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica
spec: 
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
         - nginx
  template:
   metadata:
    labels:
      app: nginx
   spec: 
     containers:
      - name: nginx-container
        image: nginx:latest
        ports: 
         - containerPort: 80