apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c2VjcmV0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: exdb
---
apiVersion: v1
kind: Pod
metadata:
  name: my-db
  labels:
    app: my-db
spec:
  containers:
    - name: my-db
      image: mysql:latest
      envFrom:
        - configMapRef:
            name: mysql-config
        - secretRef:
            name: mysql-password
      ports:
        - containerPort: 3306
